version: '3.3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf
